test:
  clj -M:test:runner

build:
  clj -X:jar

release:
  clj -M:release

release-major:
  clj -M:release major

initialize:
  git init
  git add .
  git commit -m 'Initial commit'
  git tag v0.1.0
  git remote add origin git@{{scm-domain}}:{{group}}/{{name}}.git